<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bra_person_ukd"
 *
 * Auto generated by Extension Builder 2018-07-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Personendatenbank UKD',
    'description' => 'Personendatenbank Universitätsklinikum Düsseldorf',
    'category' => 'plugin',
    'author' => 'Rolf Nakielski',
    'author_email' => 'rolf@nakielski.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
