#
# Table structure for table 'tx_brapersonukd_domain_model_person'
#
CREATE TABLE tx_brapersonukd_domain_model_person (

	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,

	old_id varchar(255) DEFAULT '' NOT NULL,
	position int(11) DEFAULT '0' NOT NULL,
	salutation varchar(255) DEFAULT '' NOT NULL,
	sex varchar(255) DEFAULT '' NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	firstname varchar(255) DEFAULT '' NOT NULL,
	lastname varchar(255) DEFAULT '' NOT NULL,
	job varchar(255) DEFAULT '' NOT NULL,
	old_image_id varchar(255) DEFAULT '' NOT NULL,
	job_title varchar(255) DEFAULT '' NOT NULL,
	country_job varchar(255) DEFAULT '' NOT NULL,
	medical_association varchar(255) DEFAULT '' NOT NULL,
	link_medical_association varchar(255) DEFAULT '' NOT NULL,
	address text NOT NULL,
	image int(11) unsigned NOT NULL default '0',
	room_nr varchar(255) DEFAULT '' NOT NULL,
	building_level varchar(255) DEFAULT '' NOT NULL,
	building_nr varchar(255) DEFAULT '' NOT NULL,
	street varchar(255) DEFAULT '' NOT NULL,
	street_nr varchar(255) DEFAULT '' NOT NULL,
	post_office_p_ost varchar(255) DEFAULT '' NOT NULL,
	country_code varchar(255) DEFAULT '' NOT NULL,
	country varchar(255) DEFAULT '' NOT NULL,
	zip_code varchar(255) DEFAULT '' NOT NULL,
	city varchar(255) DEFAULT '' NOT NULL,
	phone1 varchar(255) DEFAULT '' NOT NULL,
	phone2 varchar(255) DEFAULT '' NOT NULL,
	fax varchar(255) DEFAULT '' NOT NULL,
	mobile_phone varchar(255) DEFAULT '' NOT NULL,
	email varchar(255) DEFAULT '' NOT NULL,
	homepage varchar(255) DEFAULT '' NOT NULL,
	misc varchar(255) DEFAULT '' NOT NULL,
	person_id_fk varchar(255) DEFAULT '' NOT NULL,
	unit_id_fk varchar(255) DEFAULT '' NOT NULL,
	department_id_fk varchar(255) DEFAULT '' NOT NULL,
	homepage_title varchar(255) DEFAULT '' NOT NULL,
	homepage_page_title varchar(255) DEFAULT '' NOT NULL,
	filelink_title varchar(255) DEFAULT '' NOT NULL,
	homepage_page varchar(255) DEFAULT '' NOT NULL,
	filelink varchar(255) DEFAULT '' NOT NULL,
	email2 varchar(255) DEFAULT '' NOT NULL,

	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	crdate int(11) unsigned DEFAULT '0' NOT NULL,
	cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	starttime int(11) unsigned DEFAULT '0' NOT NULL,
	endtime int(11) unsigned DEFAULT '0' NOT NULL,

	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(255) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage int(11) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
	t3ver_move_id int(11) DEFAULT '0' NOT NULL,

	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumblob,

	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY t3ver_oid (t3ver_oid,t3ver_wsid),
	KEY language (l10n_parent,sys_language_uid)

);
